import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import "@radix-ui/themes/styles.css";
import { Container, Theme } from "@radix-ui/themes";
import './theme-config.css';
import AuthProvider from "./auth/Provider";


const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <body
        className={roboto.className}
      >
        <AuthProvider>
        <Theme accentColor="teal" radius="small" scaling="110%">
        <NavBar/>
        <main className="p-6">

        <Container>
        {children}
        </Container>  
        </main>

        </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
