import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import "@radix-ui/themes/styles.css";
import { Container, Theme } from "@radix-ui/themes";
import './theme-config.css';


const geist = Geist({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-geist",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${geistMono.variable} antialiased`}
      >
        <Theme accentColor="teal" radius="small" scaling="110%">
        <NavBar/>
        <main className="p-6">

        <Container>
        {children}
        </Container>  
        </main>

        </Theme>
        
      </body>
    </html>
  );
}
